export const TEST_ACTION = "TEST_ACTION";
export const TEST_ACTION_PENDING = "TEST_ACTION_PENDING";
export const TEST_ACTION_REJECTED = "TEST_ACTION_REJECTED";
export const TEST_ACTION_FULFILLED = "TEST_ACTION_FULFILLED";
